name: py39
channels:
  - defaults
dependencies:
  - python=3.9
  - notebook
  - numpy
  - scipy
  - pip
  - tqdm
  - matplotlib
  - scikit-image
  - seaborn
  - pip:
      - pypher
      - opencv-python
      - ipywidgets
      - rawpy
      - XlsxWriter
