name: py39
channels:
  - conda-forge
dependencies:
  - python=3.9
  - notebook=7.4.5
  - numpy=1.26.4
  - scipy=1.13.1 
  - tqdm=4.67.1
  - matplotlib=3.9.4
  - pillow=11.3.0
  - pandas=2.3.1
  - openpyxl=3.1.5
  - scikit-image=0.24.0
  - seaborn=0.13.2
  - GitPython=3.1.45
  - pyserial=3.5
  - humanize=4.12.3
  - pip
  - pip:
      - pypher==0.7.3 
      - opencv-python==4.8.1.78
      - ipywidgets==8.1.7
      - xlsxWriter==3.2.9
      - rawpy==0.25.1
      - PyExifTool==0.5.6
      - jsbeautifier==1.15.4
      - colour-demosaicing==0.2.5
      - colour-science==0.4.4
      - tkinterdnd2==0.4.3
