name: py39
channels:
  - defaults
dependencies:
  - python=3.9
  - notebook
  - numpy
  - scipy
  - tqdm
  - matplotlib
  - pillow
  - pandas
  - openpyxl
  - scikit-image
  - seaborn
  - GitPython
  - pyserial
  - humanize
  - ipywidgets
  - xlsxWriter
  - pip
  - pip:
      - pypher
      - opencv-python
      - rawpy
      - colour_demosaicing
      - colour-science
      - jsbeautifier
      - PyExifTool
