name: py312
channels:
  - conda-forge
dependencies:
  - python=3.12
  - notebook=7.4.7
  - numpy=2.2.6
  - scipy=1.16.2 
  - tqdm=4.67.1
  - matplotlib=3.10.6
  - pillow=11.3.0
  - pandas=2.3.3
  - openpyxl=3.1.5
  - scikit-image=0.25.2
  - seaborn=0.13.2
  - GitPython=3.1.45
  - pyserial=3.5
  - humanize=4.13.0
  - pypher=0.7.3
  - ipywidgets=8.1.7
  - xlsxWriter=3.2.6
  - rawpy=0.25.1
  - jsbeautifier=1.15.4
  - pip
  - pip:
      - colour-demosaicing==0.2.6
      - colour-science==0.4.6
      - opencv-python==4.12.0.88
      - tkinterdnd2==0.4.3
