name: py39
channels:
  - defaults
dependencies:
  - python=3.9
  - notebook
  - numpy
  - scipy
  - pip
  - tqdm
  - matplotlib
  - pillow
  - pandas
  - openpyxl
  - scikit-image
  - seaborn
  - GitPython
  - pyserial
  - humanize
  - pip:
      - pypher
      - opencv-python
      - ipywidgets
      - rawpy
      - XlsxWriter
      - colour_demosaicing
      - jsbeautifier
      - PyExifTool
      - pyimagej
